version: 2.1

executors:
  default:
    docker:
      - image: cimg/base:current
  dlc:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    resource_class: xlarge

orbs:
  aws-cli: circleci/aws-cli@2.1.0

workflows:
  main-workflow:
    jobs:
      - build
      - unit-test:
          requires:
            - build
#      - integration-test:
#          requires:
#            - build
      - deploy:
          requires:
#            - integration-test
            - unit-test

jobs:
  build:
    executor: dlc
    steps:
      - checkout
      - run: ./do cross
      - persist_to_workspace:
          root: .
          paths:
            - bundles
  unit-test:
    executor: dlc
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: make test-unit
      - store_test_results:
          path: bundles/
  integration-test:
    executor: dlc
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: make test-integration
      - store_test_results:
          path: bundles/
  deploy:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - aws-cli/setup:
          aws-access-key-id: BINARY_S3_AWS_ACCESS_KEY_ID
          aws-secret-access-key: BINARY_S3_AWS_SECRET_ACCESS_KEY
          profile-name: cci
      - run: ./do deploy-s3-binaries